---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress-nginx
    spec:
      rules:
      - host: nginx.cluster.local
        http:
          paths:
          - backend:
              serviceName: service-nginx
              servicePort: 80