apiVersion: v1
kind: Pod
metadata:
    name: my-web
    labels:
        env: prod
        app: main
        tier: frontend
        owner: Serhiy_Gurin
spec:
    containers:
        - name: container-apache
          image: serhiygurin/sg_web:FINAL
          ports:
            - containerPort: 80
